nameOverride: ""
fullnameOverride: ""

containerName: "tcp-echo"

image:
  registry: "docker.io"
  name: "abrarov/tcp-echo"
  tag: "latest"
  pull:
    policy: "IfNotPresent"

liveness:
  initialDelay: 2

readiness:
  initialDelay: 2

replicas: 1

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  port: 9007
  nodePort: 30007

tcpEcho:
  port: 9007
  listenBacklog: 6
  inactivityTimeout: 60
  stopTimeout: 120
  maxSessions: 10000
  bufferSize: 4096

test:
  containerName: "tcp-echo-test"
  image:
    registry: "docker.io"
    name: "busybox"
    tag: "latest"
    pull:
      policy: "IfNotPresent"
  message: "Hello World!"
