apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "tcp-echo.deploymentName" . | quote }}
  labels:
    {{- include "tcp-echo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "tcp-echo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tcp-echo.labels" . | nindent 8 }}
    spec:
      {{- if .Values.container.image.pull.secret }}
      imagePullSecrets:
        - name: {{ include "tcp-echo.imagePullSecretName" . | quote }}
      {{- end }}
      containers:
        - name: {{ .Values.container.name | quote }}
          image: {{ include "tcp-echo.containerImageFullName" . | quote }}
          imagePullPolicy: {{ .Values.container.image.pull.policy | quote }}
          args:
            - "--port"
            - {{ .Values.tcpEcho.port | quote }}
            - "--inactivity-timeout"
            - {{ .Values.tcpEcho.inactivityTimeout | default 60 | quote }}
            - "--stop-timeout"
            - {{ .Values.tcpEcho.stopTimeout | default 60 | quote }}
            - "--listen-backlog"
            - {{ .Values.tcpEcho.listenBacklog | default 6 | quote }}
            - "--max-sessions"
            - {{ .Values.tcpEcho.maxSessions | default 10000 | quote }}
            - "--buffer"
            - {{ .Values.tcpEcho.bufferSize | default 4096 | quote }}
          ports:
            - name: {{ include "tcp-echo.containerPortName" . | quote }}
              containerPort: {{ .Values.tcpEcho.port }}
          livenessProbe:
            tcpSocket:
              port: {{ include "tcp-echo.containerPortName" . | quote }}
            initialDelaySeconds: {{ .Values.container.liveness.initialDelay }}
          readinessProbe:
            tcpSocket:
              port: {{ include "tcp-echo.containerPortName" . | quote }}
            initialDelaySeconds: {{ .Values.container.readiness.initialDelay }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      terminationGracePeriodSeconds: {{ include "tcp-echo.terminationGracePeriod" . }}
