apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "tcp-echo.deploymentName" . | quote }}
  labels:
    {{- include "tcp-echo.labels" . | nindent 4 }}
    {{- include "tcp-echo.componentLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "tcp-echo.matchLabels" . | nindent 6 }}
      {{- include "tcp-echo.componentLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tcp-echo.labels" . | nindent 8 }}
        {{- include "tcp-echo.componentLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pull.secret }}
      imagePullSecrets:
        - name: {{ include "tcp-echo.imagePullSecretName" . | quote }}
      {{- end }}
      containers:
        - name: {{ .Values.containerName | quote }}
          image: {{ include "tcp-echo.imageFullName" . | quote }}
          imagePullPolicy: {{ .Values.image.pull.policy | quote }}
          args:
            - "--port"
            - {{ .Values.tcpEcho.port | quote }}
            - "--inactivity-timeout"
            - {{ .Values.tcpEcho.inactivityTimeout | default 60 | quote }}
            - "--stop-timeout"
            - {{ .Values.tcpEcho.stopTimeout | default 60 | quote }}
            - "--listen-backlog"
            - {{ .Values.tcpEcho.listenBacklog | default 6 | quote }}
            - "--max-sessions"
            - {{ .Values.tcpEcho.maxSessions | default 10000 | quote }}
            - "--buffer"
            - {{ .Values.tcpEcho.bufferSize | default 4096 | quote }}
          ports:
            - name: {{ include "tcp-echo.containerPortName" . | quote }}
              containerPort: {{ .Values.tcpEcho.port }}
          livenessProbe:
            tcpSocket:
              port: {{ include "tcp-echo.containerPortName" . | quote }}
            initialDelaySeconds: {{ .Values.liveness.initialDelay }}
          readinessProbe:
            tcpSocket:
              port: {{ include "tcp-echo.containerPortName" . | quote }}
            initialDelaySeconds: {{ .Values.readiness.initialDelay }}
          securityContext:
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            runAsNonRoot: {{ .Values.securityContext.readOnlyRootFilesystem }}
            {{- if .Values.securityContext.runAsUser }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
            {{- end }}
            {{- if .Values.securityContext.runAsGroup }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            {{- end }}
      terminationGracePeriodSeconds: {{ include "tcp-echo.terminationGracePeriod" . }}
