apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "tcp-echo.serviceName" . | quote }}
  labels:
    {{- include "tcp-echo.labels" . | nindent 4 }}
    {{- include "tcp-echo.componentLabels" . | nindent 4 }}
spec:
  type: "NodePort"
  ports:
    - name: {{ include "tcp-echo.servicePortName" . | quote }}
      port: {{ .Values.service.port }}
      targetPort: {{ include "tcp-echo.containerPortName" . | quote }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "tcp-echo.matchLabels" . | nindent 4 }}
    {{- include "tcp-echo.componentLabels" . | nindent 4 }}
