{{- if .Values.test.image.pull.secret -}}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "tcp-echo.test.imagePullSecretName" . | quote }}
  labels:
    {{- include "tcp-echo.labels" . | nindent 4 }}
    {{- include "tcp-echo.test.componentLabels" . | nindent 4 }}
type: "kubernetes.io/dockerconfigjson"
data:
  .dockerconfigjson: {{ include "tcp-echo.dockerRegistryAuthenticationConfig" (dict "imageRegistry" .Values.test.image.registry "credentials" .Values.test.image.pull.secret) | quote }}
{{- end }}
